GoogleCloudPlatform/contact-center-ai-samples

.github/workflows/dialogflow-cx-webhook-python.yaml
Resolves https://github.com/GoogleCloudPlatform/contact-center-ai-samples/issues/6
=> chore: refactor actions workflow for single linting

.github/workflows/dialogflow-cx-python.yaml, .github/workflows/scorecards.yml
Merging three commits from renovatebot that update the sha hashes on scorecards.yaml
=> Upgrade scorecards

dialogflow-cx-nodejs/revive-previous-session-state.js
Add `v3beta1` to revive session state sample
Change-Id: I0ab9ad7760237bfed6230b4e0378fc794e504309
=> fix: reformat region tag

.github/workflows/linter.yaml, .python-lint, .tflint.hcl, dialogflow-cx/terraform/main.tf, noxfile.py, oidc/main.tf, tasks.py
=> Repair broken linting config tooling to keep up-to-date using pyinvoke

.github/workflows/vpc-sc-auth-server.yaml, .github/workflows/vpc-sc-demo.yaml, dialogflow-cx/vpc-sc-auth-server/server/session.py, dialogflow-cx/vpc-sc-auth-server/server/test_app.py, dialogflow-cx/vpc-sc-auth-server/server/test_session.py, noxfile.py
Avoids returning information vulnerable to exposure.
=> Fix #137 Replace response with specific error message

.github/workflows/vpc-sc-auth-server.yaml, .github/workflows/vpc-sc-demo.yaml
=> Fix several pinned dependency issues

.gitignore, dialogflow-cx/vpc-sc-demo/Dockerfile, dialogflow-cx/vpc-sc-demo/backend/get_token.py, dialogflow-cx/vpc-sc-demo/backend/status_utilities.py, dialogflow-cx/vpc-sc-demo/backend/test_get_token.py, dialogflow-cx/vpc-sc-demo/backend/test_launchpad_blueprint.py, dialogflow-cx/vpc-sc-demo/backend/test_status_utilities.py, dialogflow-cx/vpc-sc-demo/debug.sh
Some potential errors with the module are flagged; the strategy is to get all the codepaths protected with hermetic unit tests, and then circle back to refactor; none of the potential bugs appear to impact current production environment.
=> Add status_utilities module with tests for each codepath

dialogflow-cx/vpc-sc-demo/components/reverse_proxy_server/main.tf, dialogflow-cx/vpc-sc-demo/components/reverse_proxy_server/startup_script.sh, dialogflow-cx/vpc-sc-demo/components/reverse_proxy_server/wait_until_server_ready.sh, dialogflow-cx/vpc-sc-demo/deploy/.terraformrc, dialogflow-cx/vpc-sc-demo/deploy/terraform/main.tf, dialogflow-cx/vpc-sc-demo/deploy/terraform/service-directory/main.tf, dialogflow-cx/vpc-sc-demo/deploy/terraform/service-perimeter/main.tf, dialogflow-cx/vpc-sc-demo/deploy/terraform/services/main.tf, dialogflow-cx/vpc-sc-demo/deploy/terraform/vpc-network/main.tf, dialogflow-cx/vpc-sc-demo/deploy/terraform/vpc-network/startup_script.sh, dialogflow-cx/vpc-sc-demo/deploy/terraform/vpc-network/wait_until_server_ready.sh, dialogflow-cx/vpc-sc-demo/deploy/terraform/webhook-agent/deploy_agent.sh, dialogflow-cx/vpc-sc-demo/deploy/terraform/webhook-agent/main.tf
These submodules have not yet been tested in production, but roll in all the improvements addressed in the components work.
=> Add terraform deploy plans

dialogflow-cx/vpc-sc-demo/backend/conftest.py, dialogflow-cx/vpc-sc-demo/backend/session_blueprint.py, dialogflow-cx/vpc-sc-demo/backend/session_utilities.py, dialogflow-cx/vpc-sc-demo/backend/test_asset_blueprint.py, dialogflow-cx/vpc-sc-demo/backend/test_launchpad_blueprint.py, dialogflow-cx/vpc-sc-demo/backend/test_session_blueprint.py, dialogflow-cx/vpc-sc-demo/backend/test_session_utilities.py, dialogflow-cx/vpc-sc-demo/backend/test_status_blueprint.py
Refactor tests to use common app fixture, indirect parametrization.
=> Add session_utilities module. 

dialogflow-cx/vpc-sc-demo/backend/asset_blueprint.py, dialogflow-cx/vpc-sc-demo/backend/asset_utilities.py, dialogflow-cx/vpc-sc-demo/backend/test_asset_utilities.py
Create a utility function for setting the terraform debug mode.
=> Debug mode

dialogflow-cx/vpc-sc-demo/backend/asset_utilities.py, dialogflow-cx/vpc-sc-demo/frontend/src/AssetPollToggle.js, dialogflow-cx/vpc-sc-demo/frontend/src/DataModel.js
The submodule location of artifactregistry service resource needs to be updated so that it can be deployed via the frontend.
=> Artifactregistry location

dialogflow-cx/vpc-sc-demo/frontend/src/QueryPrincipal.js
Small bug fix on data type of shrink in get_principal
=> Shrink principal

.gitignore, dialogflow-cx/vpc-sc-demo/components/reverse_proxy_server/main.tf, dialogflow-cx/vpc-sc-demo/deploy/terraform/vpc-network/main.tf
Add additional IAM permissions on reverse proxy server VM to access storage bucket, allowing certificate storage.
=> Reverse Proxy Server permissions:

dialogflow-cx/vpc-sc-demo/frontend/src/SettingsPanel.js
Update shrink setting on access_policy to format correctly
=> Shrink access policy

.github/workflows/vpc-sc-demo-terraform.yaml, dialogflow-cx/vpc-sc-demo/deploy/terraform/Dockerfile, dialogflow-cx/vpc-sc-demo/deploy/terraform/main.tf, dialogflow-cx/vpc-sc-demo/deploy/terraform/requirements-test.txt, dialogflow-cx/vpc-sc-demo/deploy/terraform/test_runner.sh, dialogflow-cx/vpc-sc-demo/deploy/terraform/test_terraform_module.py
Adds infrastructure that is necessary to test the topology of the terraform module, using terraform graph
=> Test terraform module

dialogflow-cx/vpc-sc-demo/backend/asset_blueprint.py, dialogflow-cx/vpc-sc-demo/backend/asset_utilities.py, dialogflow-cx/vpc-sc-demo/backend/test_asset_blueprint.py, dialogflow-cx/vpc-sc-demo/backend/test_asset_utilities.py, dialogflow-cx/vpc-sc-demo/frontend/src/AssetPollToggle.js, dialogflow-cx/vpc-sc-demo/frontend/src/DataModel.js, dialogflow-cx/vpc-sc-demo/frontend/src/SettingsPanel.js, dialogflow-cx/vpc-sc-demo/frontend/src/Utilities.js
This PR reimplements the way that setting project_id is performed, and is much more reliable and stable, following the system for access_policy_title.
=> Project id when return is pressed.

dialogflow-cx/vpc-sc-demo/backend/conftest.py, dialogflow-cx/vpc-sc-demo/backend/get_token.py, dialogflow-cx/vpc-sc-demo/backend/test_get_token.py
Fixes #236 
Better error handling if there is an error during decryption. If valueerror, will expire session_id cookie.
=> Fix Issue/236 Better error handling during decoding

.gitignore, dialogflow-cx/vpc-sc-auth-server/config.env, dialogflow-cx/vpc-sc-auth-server/deploy.sh, dialogflow-cx/vpc-sc-demo/config.env, dialogflow-cx/vpc-sc-demo/deploy.sh
Fix #241 by tagging each push with a "r-[github short hash]". Makes debugging easier.
=> Fixes #241

dialogflow-cx/vpc-sc-demo/frontend/src/AssetPollToggle.js
=> Fixes #248 by removing destroy restriction when planning the targets

dialogflow-cx/vpc-sc-demo/backend/get_token.py, dialogflow-cx/vpc-sc-demo/frontend/src/AssetPollToggle.js, dialogflow-cx/vpc-sc-demo/frontend/src/StatusPollToggle.js
Fix #254 and and also addresses a race condition in the updating of asset switches
=> Fixes #254 tf blocked
